# ============================================================================
# Netrw Directory Listing                                        (netrw v173)
# This section shows the file directory listing generated by Netrw, a Vim plugin
# for browsing files. It displays the contents of the directory 
# /Users/admin/portfolio/api/orders.
# 
# Sorted by      name
# Files and directories are sorted alphabetically by name.
# 
# Sort sequence: [\/]$,\<core\%(\.\d\+\)\=\>,\.h$,\.c$,\.cpp$,\~\=\*$,*,\.o$,
# The sort sequence determines the order in which file types are listed, 
# prioritizing certain extensions and patterns.
# 
# Quick Help: <F1>:help  -:go up dir  D:delete  R:rename  s:sort-by  x:special
# Quick help instructions for using Netrw in Vim, including common commands.
# ============================================================================
../                               0 Mer 28 aoû 20:53:57 2024  # Parent directory
./                                0 Mer 28 aoû 23:05:55 2024  # Current directory
__init__.py                       0 Mar 27 aoû 17:41:05 2024  # Initialization file for the Python package
__pycache__/                      0 Mer 28 aoû 20:53:57 2024  # Directory containing compiled Python bytecode
views.py                          5400 Mer 28 aoû 20:53:57 2024  # Python file containing views, 5400 bytes in size
~  # End of the file list, a standard Vim display feature in empty lines

